services:
  pwa-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL:-http://localhost:3001}
        VITE_APP_NAME: ${VITE_APP_NAME:-Medienausleihe OTH-AW}
    container_name: medienausleihe-app
    ports:
      - "${APP_PORT:-8080}:80"
    restart: unless-stopped
    networks:
      - ausleihe

networks:
  ausleihe:
    external: true