services:
  pwa-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Build-time Variablen für Frontend-Konfiguration
        VITE_SERVER_URL: ${VITE_SERVER_URL:-http://95.175.98.147:3001}
        VITE_GOOGLE_CALENDAR_API_KEY: ${VITE_GOOGLE_CALENDAR_API_KEY:-}
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY:-}
        VITE_APP_NAME: ${VITE_APP_NAME:-Medienausleihe OTH-AW}
        VITE_APP_SHORT_NAME: ${VITE_APP_SHORT_NAME:-Medienausleihe}
        VITE_APP_DESCRIPTION: ${VITE_APP_DESCRIPTION:-Medienausleihe System der OTH Amberg-Weiden}
    container_name: medienausleihe-app
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

# Standard Docker-Netzwerk